spring.application.name=sidep-backend

# localhost
spring.datasource.url=jdbc:mysql://localhost:3306/sidep-db
spring.datasource.username=root
spring.datasource.password=fK490&G48nv

# desarrollo
# spring.datasource.url=jdbc:mysql://sidepdbinstance.cbs6uw6gsxc7.us-east-2.rds.amazonaws.com:3306/sidep-db
# spring.datasource.username=admin
# spring.datasource.password=m4nu1F3r

server.port=8443
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=classpath:keystore/baeldung.p12
# server.ssl.key-store-password=ferdimen16
# server.ssl.key-alias=baeldung
# server.ssl.enabled=true

# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.driver-class-name=com.mysql.jdbc.Driver
